### PR TITLE
add documentation to show we have added a unique identifer to the use…

### PR DESCRIPTION
**Pull request by pivotal-Jammy-Louie**
…r ids [#154063041]

Signed-off-by: Jammy Louie <jlouie@pivotal.io>

### CODE REVIEW

**Comment by pivotal-Jammy-Louie** [comment]
Changes Made

**Comment by karensmolermiller** [comment]
Thanks Jammy and Megan.

**Comment by cf-meganmoore** [comment]
@karensmolermiller are we keeping this branch for some reason, now that the content has been merged? Or can the branch be deleted?

**Comment by karensmolermiller** [comment]
@cf-meganmoore I just don't know your standard process.  I believe that the branch can be removed from the repo.  Maybe contact me via slack or email.  You remove the feature branch as soon as you merge in changes?

**Comment by jncd** [comment]
@karensmolermiller Yes, we try to delete the PR branches after the merge. Otherwise they proliferate and it's hard to find the important branches in the list. 
Also, these are so easy to get back with the "Restore branch" button that I don't worry about deleting.

**Pull request merged**
