### PR TITLE
Adds declaration of support for IPSec addon

### PR DESCRIPTION
**Pull request by xtreme-gavin-enns**
includes link to IPSec for pcf general docs

@cf-meganmoore

### CODE REVIEW

**Comment by cf-meganmoore** [comment]
thanks @xtreme-gavin-enns ! looks good.

**Comment by cf-meganmoore** [comment]
hey @xtreme-gavin-enns  - just to be sure: you wanted this commit to be merged into master, not into the 1.2 docs?

**Comment by xtreme-gavin-enns** [comment]
No I think you're right, this should be for 1.2

@astrieanna can confirm?

**Comment by zmb3** [comment]
Should 
```
    <tr>
         <td>IPsec support</td>
         <td>No</td>		      
     </tr>
```

Have also been updated here?

**Comment by cf-meganmoore** [comment]
@zmb3 can you please elaborate? would need more specific details on what you want updated.

**Comment by cf-meganmoore** [comment]
@zmb3 never mind! I got the info. thank you.  :)

**Pull request merged**
