### PR TITLE
Added warning about data loss on adding AZ to plans.

### PR DESCRIPTION
**Pull request by badie**
[#144555253]

Signed-off-by: Afolabi Badmos <abadmos@pivotal.io>

### CODE REVIEW

**Comment by cf-meganmoore** [comment]
thanks for adding this.

**Comment by pulkitpivotal** [comment]
@cf-meganmoore We do need to cherry pick this to master. Best would have been to create pull requests on both master and 1.0-branch

**Comment by pulkitpivotal** [comment]
@cf-meganmoore Is there a way we could make the warning come in a box?

**Comment by cf-meganmoore** [comment]
hi @pulkitpivotal ! This change has been cherry picked to master. Also, fyi, the "Warning" note is enclosed in a box when it appears in production.

**Pull request merged**
